# -*- coding: utf-8 -*-
"""Genetic algorithm and its application

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PY1flOnJkQNNNzNSBPUVDwUNJyUkGGD2
"""

import random

# --- 1. NETWORK TOPOLOGY SETUP (SYNTAX-SAFE DICTIONARY) ---
# Format: { node: { neighbor_node: latency_in_ms, ... } }
NETWORK_GRAPH = {
    0: {1: 5, 2: 2},        # Node 0 (Source) connects to 1 and 2
    1: {0: 5, 2: 1, 3: 4},  # Node 1 connects to 0, 2, and 3
    2: {0: 2, 1: 1, 3: 6, 4: 2}, # Node 2 connects to 0, 1, 3, and 4
    3: {1: 4, 2: 6, 4: 1, 5: 3}, # Node 3 connects to 1, 2, 4, and 5
    4: {2: 2, 3: 1, 5: 7},  # Node 4 connects to 2, 3, and 5
    5: {3: 3, 4: 7}         # Node 5 (Destination) connects to 3 and 4
}

START_NODE = 0
END_NODE = 5

# --- 2. GA CONFIGURATION PARAMETERS ---
POP_SIZE = 50
GENERATIONS = 40
CROSSOVER_RATE = 0.8
MUTATION_RATE = 0.3

# --- 3. CORE ROUTING GA FUNCTIONS ---

def get_neighbors(node):
    """Returns directly connected neighbors from the dictionary."""
    return list(NETWORK_GRAPH.get(node, {}).keys())

def create_individual():
    """Generates a random valid path from START_NODE to END_NODE."""
    path = [START_NODE]
    current = START_NODE
    visited = {START_NODE}

    max_steps = len(NETWORK_GRAPH) * 2
    steps = 0

    while current != END_NODE and steps < max_steps:
        neighbors = [n for n in get_neighbors(current) if n not in visited]
        if not neighbors:
            path = [START_NODE]
            current = START_NODE
            visited = {START_NODE}
            steps = 0
            continue

        next_node = random.choice(neighbors)
        path.append(next_node)
        visited.add(next_node)
        current = next_node
        steps += 1

    return path

def fitness_function(path):
    """Evaluates path latency. Returns (1 / total_latency) to maximize."""
    if not path or path[0] != START_NODE or path[-1] != END_NODE:
        return 0.0001

    total_latency = 0
    for i in range(len(path) - 1):
        current = path[i]
        nxt = path[i+1]

        if nxt not in NETWORK_GRAPH[current]:
            return 0.0001
        total_latency += NETWORK_GRAPH[current][nxt]

    return 1.0 / total_latency

def tournament_selection(population, fitness_scores, k=3):
    selection_ix = random.randint(0, len(population) - 1)
    for ix in random.sample(range(len(population)), k - 1):
        if fitness_scores[ix] > fitness_scores[selection_ix]:
            selection_ix = ix
    return population[selection_ix]

def crossover(parent1, parent2):
    """Finds a shared intermediate node to swap routes safely."""
    if random.random() < CROSSOVER_RATE:
        common_nodes = set(parent1[1:-1]) & set(parent2[1:-1])

        if common_nodes:
            shared_node = random.choice(list(common_nodes))
            idx1 = parent1.index(shared_node)
            idx2 = parent2.index(shared_node)

            child1 = parent1[:idx1] + parent2[idx2:]
            child2 = parent2[:idx2] + parent1[idx1:]

            return remove_loops(child1), remove_loops(child2)

    return parent1.copy(), parent2.copy()

def mutate(path):
    """Mutates path from a random intermediate point onward."""
    if random.random() < MUTATION_RATE and len(path) > 2:
        mutation_point = random.randint(1, len(path) - 2)
        new_path = path[:mutation_point]
        current = new_path[-1]
        visited = set(new_path)

        for _ in range(len(NETWORK_GRAPH)):
            if current == END_NODE:
                break
            neighbors = [n for n in get_neighbors(current) if n not in visited]
            if not neighbors:
                return
            next_node = random.choice(neighbors)
            new_path.append(next_node)
            visited.add(next_node)
            current = next_node

        if new_path[-1] == END_NODE:
            path[:] = new_path

def remove_loops(path):
    clean_path = []
    for node in path:
        if node in clean_path:
            idx = clean_path.index(node)
            clean_path = clean_path[:idx + 1]
        else:
            clean_path.append(node)
    return clean_path

# --- 4. MAIN EVOLUTION LOOP ---

def main():
    population = [create_individual() for _ in range(POP_SIZE)]
    best_path = None
    best_fitness = -1

    for generation in range(GENERATIONS):
        fitness_scores = [fitness_function(ind) for ind in population]

        for i in range(POP_SIZE):
            if fitness_scores[i] > best_fitness:
                best_fitness = fitness_scores[i]
                best_path = population[i].copy()

        if generation % 10 == 0:
            current_latency = 1.0 / best_fitness if best_fitness > 0 else float('inf')
            print(f"Generation {generation}: Optimal Path Latency = {current_latency:.1f} ms")

        next_generation = []
        while len(next_generation) < POP_SIZE:
            p1 = tournament_selection(population, fitness_scores)
            p2 = tournament_selection(population, fitness_scores)

            c1, c2 = crossover(p1, p2)
            mutate(c1)
            mutate(c2)

            next_generation.extend([c1, c2])

        population = next_generation[:POP_SIZE]

    print("\n--- Routing Optimization Finished ---")
    print(f"Best Optimized Path: {best_path}")
    print(f"Minimum Total Latency: {1.0 / best_fitness:.1f} ms")

if __name__ == "__main__":
    main()