# -*- coding: utf-8 -*-
"""PSO And its application ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1go9k_TyNlleHIPuaaqkSKC2p2oTpIYNi
"""

import numpy as np
import random  # FIX: Use Python's built-in random module to keep integers clean

# 1. Define the Problem (Network Topology Graph)
INF = np.inf
graph = np.array([
    [0,   4,   2,   INF, INF, INF],  # Node 0 (Source)
    [4,   0,   1,   5,   INF, INF],  # Node 1
    [2,   1,   0,   8,   10,  INF],  # Node 2
    [INF, 5,   8,   0,   2,   6],    # Node 3
    [INF, INF, 10,  2,   0,   3],    # Node 4
    [INF, INF, INF, 6,   3,   0]     # Node 5 (Destination)
])

source_node = 0
dest_node = 5
num_nodes = len(graph)

def evaluate_path_cost(path):
    cost = 0
    for i in range(len(path) - 1):
        u, v = path[i], path[i+1]
        if graph[u][v] == INF:
            return INF
        cost += graph[u][v]
    return cost

def generate_random_path(source, dest, max_length=10):
    path = [source]
    current = source
    visited = {source}

    while current != dest and len(path) < max_length:
        neighbors = np.where(graph[current] != INF)[0]
        neighbors = [int(n) for n in neighbors if int(n) not in visited]

        if not neighbors:
            break
        # FIX: Use native random.choice to prevent np.int64 conversion
        current = random.choice(neighbors)
        path.append(current)
        visited.add(current)

    if path[-1] != dest:
        path.append(dest)
    return path

# 2. Initialize Parameters
num_particles = 40
max_iterations = 60
p_social = 0.4
p_cognitive = 0.3

# 3. Initialize Swarm
swarm_positions = [generate_random_path(source_node, dest_node) for _ in range(num_particles)]
pbest_paths = list(swarm_positions)
pbest_costs = [evaluate_path_cost(p) for p in pbest_paths]

gbest_idx = np.argmin(pbest_costs)
gbest_path = list(pbest_paths[gbest_idx])
gbest_cost = pbest_costs[gbest_idx]

# 5. Velocity/Update Logic for Paths
def update_path(pbest, gbest):
    new_path = [source_node]
    curr = source_node
    visited = {source_node}

    while curr != dest_node and len(new_path) < 15:
        r = np.random.rand()
        next_node = None

        # Social influence
        if r < p_social and curr in gbest:
            idx = gbest.index(curr)
            if idx < len(gbest) - 1:
                next_node = int(gbest[idx + 1])

        # Cognitive influence
        elif r < (p_social + p_cognitive) and curr in pbest:
            idx = pbest.index(curr)
            if idx < len(pbest) - 1:
                next_node = int(pbest[idx + 1])

        # Fallback Exploration (Avoiding loops)
        if next_node is None or graph[curr][next_node] == INF or next_node in visited:
            neighbors = np.where(graph[curr] != INF)[0]
            neighbors = [int(n) for n in neighbors if int(n) not in visited]
            if not neighbors:
                break
            # FIX: Use native random.choice here as well
            next_node = random.choice(neighbors)

        new_path.append(next_node)
        visited.add(next_node)
        curr = next_node

    if new_path[-1] != dest_node:
        new_path.append(dest_node)
    return new_path

# 6. Optimization Loop
for iteration in range(max_iterations):
    for i in range(num_particles):
        swarm_positions[i] = update_path(pbest_paths[i], gbest_path)
        cost = evaluate_path_cost(swarm_positions[i])

        if cost < pbest_costs[i]:
            pbest_costs[i] = cost
            pbest_paths[i] = list(swarm_positions[i])

        if cost < gbest_cost:
            gbest_cost = cost
            gbest_path = list(swarm_positions[i])

# 7. Output Clean Result
print(f"Optimal Routing Path: {gbest_path}")
print(f"Minimum Path Cost (Latency/Distance): {gbest_cost}")